#include "Utils/TIRLogCategories.h"

DEFINE_LOG_CATEGORY(LogTIRCore);
DEFINE_LOG_CATEGORY(LogTIRCombat);
DEFINE_LOG_CATEGORY(LogTIRMovement);
DEFINE_LOG_CATEGORY(LogTIRAi);
DEFINE_LOG_CATEGORY(LogTIRProgression);
DEFINE_LOG_CATEGORY(LogTIRSpawning);
DEFINE_LOG_CATEGORY(LogTIRUi);