#pragma once

#include "CoreMinimal.h"

TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRCore, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRCombat, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRMovement, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRAi, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRProgression, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRSpawning, Log, All);
TIRCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogTIRUi, Log, All);